2018-04-22T04:19:44.334Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID '1' in collection with ID 'Asset:org.audit.loan.Loan' does not exist)
    at /home/zia/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-22T04:19:44.337Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID '1' in collection with ID 'Asset:org.audit.loan.Loan' does not exist)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID '1' in collection with ID 'Asset:org.audit.loan.Loan' does not exist)\n\n    at _initializeChannel.then.then.then.then.catch (/home/zia/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
